//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickStarts.EndpointCatalog.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickStarts.EndpointCatalog.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration for endpoint &apos;{0}&apos;.
        /// </summary>
        internal static string ConfigurationForEndpoint {
            get {
                return ResourceManager.GetString("ConfigurationForEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoints found: {0}.
        /// </summary>
        internal static string EndpointsFound {
            get {
                return ResourceManager.GetString("EndpointsFound", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (No configuration found for the specified network).
        /// </summary>
        internal static string NoConfigurationFoundForSpecifiedNetwork {
            get {
                return ResourceManager.GetString("NoConfigurationFoundForSpecifiedNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This endpoint contains configurations for the following networks: (Default), Work, Internet..
        /// </summary>
        internal static string WebService1 {
            get {
                return ResourceManager.GetString("WebService1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This endpoint contains configurations for the following networks: (Default), Internet..
        /// </summary>
        internal static string WebService2 {
            get {
                return ResourceManager.GetString("WebService2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This endpoint contains configurations for the following networks: (Default), Work..
        /// </summary>
        internal static string WebService3 {
            get {
                return ResourceManager.GetString("WebService3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This endpoint contains configurations for the following networks: (Default)..
        /// </summary>
        internal static string WebService4 {
            get {
                return ResourceManager.GetString("WebService4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This endpoint contains configurations for the following networks: Work..
        /// </summary>
        internal static string WebService5 {
            get {
                return ResourceManager.GetString("WebService5", resourceCulture);
            }
        }
    }
}
