//===============================================================================
// Microsoft patterns & practices
// Smart Client Software Factory 2010
//===============================================================================
// Copyright (c) Microsoft Corporation.  All rights reserved.
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY
// OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT
// LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
// FITNESS FOR A PARTICULAR PURPOSE.
//===============================================================================
// The example companies, organizations, products, domain names,
// e-mail addresses, logos, people, places, and events depicted
// herein are fictitious.  No association with any real company,
// organization, product, domain name, email address, logo, person,
// places, or events is intended or should be inferred.
//===============================================================================
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 
using System.CodeDom.Compiler;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

namespace GlobalBankServices
{
	/// <remarks/>
	// CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
	[GeneratedCode("wsdl", "2.0.50727.42")]
	[WebServiceBinding(Name = "BasicHttpBinding_ICustomerFinder", Namespace = "http://tempuri.org/")]
	public interface IBasicHttpBinding_ICustomerFinder
	{

		/// <remarks/>
		[WebMethod()]
		[SoapDocumentMethod("AddCustomer", RequestNamespace = "http://GlobalBranchServicesServiceContracts/2006/04/ICustomerFinder", ResponseNamespace = "http://GlobalBranchServicesServiceContracts/2006/04/ICustomerFinder", Use = SoapBindingUse.Literal, ParameterStyle = SoapParameterStyle.Wrapped)]
		[return: XmlElement(IsNullable = true)]
		string AddCustomer([XmlElement(IsNullable = true)] Customer customer);

		/// <remarks/>
		[WebMethod()]
		[SoapDocumentMethod("DeleteCustomer", RequestNamespace = "http://GlobalBranchServicesServiceContracts/2006/04/ICustomerFinder", ResponseNamespace = "http://GlobalBranchServicesServiceContracts/2006/04/ICustomerFinder", Use = SoapBindingUse.Literal, ParameterStyle = SoapParameterStyle.Wrapped)]
		[return: XmlElement(IsNullable = true)]
		DeleteCustomerResponse DeleteCustomer([XmlElement(IsNullable = true)] DeleteCustomerRequest customerToDelete);

		/// <remarks/>
		[WebMethod()]
		[SoapDocumentMethod("FindCustomer", RequestNamespace = "http://GlobalBranchServicesServiceContracts/2006/04/ICustomerFinder", ResponseNamespace = "http://GlobalBranchServicesServiceContracts/2006/04/ICustomerFinder", Use = SoapBindingUse.Literal, ParameterStyle = SoapParameterStyle.Wrapped)]
		[return: XmlElement(IsNullable = true)]
		FindCustomerResponse FindCustomer([XmlElement(IsNullable = true)] CustomerSearchCriteria searchCriteria);
	}

}