//===============================================================================
// Microsoft patterns & practices
// Smart Client Software Factory 2010
//===============================================================================
// Copyright (c) Microsoft Corporation.  All rights reserved.
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY
// OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT
// LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
// FITNESS FOR A PARTICULAR PURPOSE.
//===============================================================================
// The example companies, organizations, products, domain names,
// e-mail addresses, logos, people, places, and events depicted
// herein are fictitious.  No association with any real company,
// organization, product, domain name, email address, logo, person,
// places, or events is intended or should be inferred.
//===============================================================================
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 
using System.CodeDom.Compiler;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

namespace GlobalBankServices
{

	/// <remarks/>
	// CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
	[GeneratedCode("wsdl", "2.0.50727.42")]
	[WebServiceBinding(Name = "BasicHttpBinding_ICustomerQueue", Namespace = "http://tempuri.org/")]
	public interface IBasicHttpBinding_ICustomerQueue
	{
		[WebMethod()]
		[SoapDocumentMethod("AddToQueue", RequestNamespace = "http://GlobalBranchServicesServiceContracts/2006/04/CustomerQueue", ResponseNamespace = "http://GlobalBranchServicesServiceContracts/2006/04/CustomerQueue", Use = SoapBindingUse.Literal, ParameterStyle = SoapParameterStyle.Wrapped)]
		void AddToQueue(QueueEntry queueEntry);

		[WebMethod()]
		[SoapDocumentMethod("AssignToServicing", RequestNamespace = "http://GlobalBranchServicesServiceContracts/2006/04/CustomerQueue", ResponseNamespace = "http://GlobalBranchServicesServiceContracts/2006/04/CustomerQueue", Use = SoapBindingUse.Literal, ParameterStyle = SoapParameterStyle.Wrapped)]
		void AssignToServicing(AssignToServicingRequest request);

		/// <remarks/>
		[WebMethod()]
		[SoapDocumentMethod("GetEntries", RequestNamespace = "http://GlobalBranchServicesServiceContracts/2006/04/CustomerQueue", ResponseNamespace = "http://GlobalBranchServicesServiceContracts/2006/04/CustomerQueue", Use = SoapBindingUse.Literal, ParameterStyle = SoapParameterStyle.Wrapped)]
		[return: XmlArray(IsNullable = true)]
		[return: XmlArrayItem(Namespace = "http://GlobalBranchServicesDataContracts/2006/04/QueueEntry")]
		QueueEntry[] GetEntries(GetEntriesRequest request);

		/// <remarks/>
		[WebMethod()]
		[SoapDocumentMethod("RemoveFromQueue", RequestNamespace = "http://GlobalBranchServicesServiceContracts/2006/04/CustomerQueue", ResponseNamespace = "http://GlobalBranchServicesServiceContracts/2006/04/CustomerQueue", Use = SoapBindingUse.Literal, ParameterStyle = SoapParameterStyle.Wrapped)]
		[return: XmlElement(IsNullable = true)]
		QueueEntry RemoveFromQueue(QueueEntry entry);


	}

}
