
//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add View" recipe.
//
// For more information see: 
// ms-help://MS.VSCC.v90/MS.VSIPCC.v90/ms.practices.scsf.2008apr/SCSF/html/02-09-010-ModelViewPresenter_MVP.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace QuickStart.RestaurantModule
{
    partial class MenuItemsView
    {
        /// <summary>
        /// The presenter used by this view.
        /// </summary>
        private QuickStart.RestaurantModule.MenuItemsViewPresenter _presenter = null;

        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (_presenter != null)
                    _presenter.Dispose();

                if (components != null)
                    components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.Windows.Forms.ListViewGroup listViewGroup1 = new System.Windows.Forms.ListViewGroup("Menu", System.Windows.Forms.HorizontalAlignment.Left);
            this._menuItemsListView = new System.Windows.Forms.ListView();
            this._errorLabel = new System.Windows.Forms.Label();
            this._retryLabel = new System.Windows.Forms.LinkLabel();
            this._offlineLabel = new System.Windows.Forms.Label();
            this.SuspendLayout();
            // 
            // _menuItemsListView
            // 
            this._menuItemsListView.BackColor = System.Drawing.SystemColors.Window;
            this._menuItemsListView.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this._menuItemsListView.Dock = System.Windows.Forms.DockStyle.Fill;
            listViewGroup1.Header = "Menu";
            listViewGroup1.Name = "menuGroup";
            this._menuItemsListView.Groups.AddRange(new System.Windows.Forms.ListViewGroup[] {
            listViewGroup1});
            this._menuItemsListView.Location = new System.Drawing.Point(0, 0);
            this._menuItemsListView.Name = "_menuItemsListView";
            this._menuItemsListView.Size = new System.Drawing.Size(335, 269);
            this._menuItemsListView.TabIndex = 1;
            this._menuItemsListView.UseCompatibleStateImageBehavior = false;
            // 
            // _errorLabel
            // 
            this._errorLabel.Dock = System.Windows.Forms.DockStyle.Top;
            this._errorLabel.Location = new System.Drawing.Point(0, 0);
            this._errorLabel.Name = "_errorLabel";
            this._errorLabel.Size = new System.Drawing.Size(335, 23);
            this._errorLabel.TabIndex = 2;
            this._errorLabel.Text = "There has been an error contacting the back-end service.";
            this._errorLabel.Visible = false;
            // 
            // _retryLabel
            // 
            this._retryLabel.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this._retryLabel.Location = new System.Drawing.Point(3, 23);
            this._retryLabel.Name = "_retryLabel";
            this._retryLabel.Size = new System.Drawing.Size(329, 23);
            this._retryLabel.TabIndex = 3;
            this._retryLabel.TabStop = true;
            this._retryLabel.Text = "Click here to Retry.";
            this._retryLabel.Visible = false;
            this._retryLabel.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this._retryLabel_LinkClicked);
            // 
            // _offlineLabel
            // 
            this._offlineLabel.Dock = System.Windows.Forms.DockStyle.Top;
            this._offlineLabel.Location = new System.Drawing.Point(0, 23);
            this._offlineLabel.Name = "_offlineLabel";
            this._offlineLabel.Size = new System.Drawing.Size(335, 13);
            this._offlineLabel.TabIndex = 4;
            this._offlineLabel.Text = "You are working in offline mode. Please connect and try again.";
            this._offlineLabel.Visible = false;
            // 
            // MenuItemsView
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.SystemColors.Window;
            this.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.Controls.Add(this._offlineLabel);
            this.Controls.Add(this._retryLabel);
            this.Controls.Add(this._errorLabel);
            this.Controls.Add(this._menuItemsListView);
            this.Name = "MenuItemsView";
            this.Size = new System.Drawing.Size(335, 269);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.ListView _menuItemsListView;
        private System.Windows.Forms.Label _errorLabel;
        private System.Windows.Forms.LinkLabel _retryLabel;
        private System.Windows.Forms.Label _offlineLabel;
    }
}

