//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Practices.SmartClientFactory.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Practices.SmartClientFactory.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Web References or Project..
        /// </summary>
        internal static string AllWebReferencesOrProject {
            get {
                return ResourceManager.GetString("AllWebReferencesOrProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This project cannot be converted to WPF..
        /// </summary>
        internal static string CannotConvertProject {
            get {
                return ResourceManager.GetString("CannotConvertProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to checkout the file {0}..
        /// </summary>
        internal static string CheckoutException {
            get {
                return ResourceManager.GetString("CheckoutException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} from file {1} has not been compiled yet. Recompile project and retry..
        /// </summary>
        internal static string ClassNotCompiledYet {
            get {
                return ResourceManager.GetString("ClassNotCompiledYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The class is not valid.
        /// </summary>
        internal static string ClassNotExists {
            get {
                return ResourceManager.GetString("ClassNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A class is required..
        /// </summary>
        internal static string ClassRequired {
            get {
                return ResourceManager.GetString("ClassRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.Practices.SmartClient.ConnectionMonitor.Configuration.ConnectionSettingsSection, Microsoft.Practices.SmartClient.ConnectionMonitor.
        /// </summary>
        internal static string ConnectionSettingsSectionType {
            get {
                return ResourceManager.GetString("ConnectionSettingsSectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The behavior for a method can only be defined once..
        /// </summary>
        internal static string DuplicatedMethodBehavior {
            get {
                return ResourceManager.GetString("DuplicatedMethodBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint name cannot be empty.
        /// </summary>
        internal static string EndpointRequired {
            get {
                return ResourceManager.GetString("EndpointRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.Practices.SmartClient.EndpointCatalog.Configuration.EndpointSection, Microsoft.Practices.SmartClient.EndpointCatalog.
        /// </summary>
        internal static string EndpointsSectionType {
            get {
                return ResourceManager.GetString("EndpointsSectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration is not valid.
        /// </summary>
        internal static string ExpirationNotValid {
            get {
                return ResourceManager.GetString("ExpirationNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder is not valid.
        /// </summary>
        internal static string FolderNotExists {
            get {
                return ResourceManager.GetString("FolderNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module name must be a valid identifier.
        /// </summary>
        internal static string ModuleNameMustBeValidIdentifier {
            get {
                return ResourceManager.GetString("ModuleNameMustBeValidIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module name cannot be empty.
        /// </summary>
        internal static string ModuleNameRequired {
            get {
                return ResourceManager.GetString("ModuleNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.contoso.com.
        /// </summary>
        internal static string NetworkAddress {
            get {
                return ResourceManager.GetString("NetworkAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet.
        /// </summary>
        internal static string NetworkName {
            get {
                return ResourceManager.GetString("NetworkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current selection is not a web reference, or the containing project has not been compiled since the web reference was added. Recompile project and retry..
        /// </summary>
        internal static string NoProxyFound {
            get {
                return ResourceManager.GetString("NoProxyFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one selected method is needed..
        /// </summary>
        internal static string OneSelectedMethodNeeded {
            get {
                return ResourceManager.GetString("OneSelectedMethodNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either an owning project or item must be specified..
        /// </summary>
        internal static string OwnerProjectOrItemRequired {
            get {
                return ResourceManager.GetString("OwnerProjectOrItemRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You attempted to update a disconnected service agent that uses the Web service proxy type {0}, but the current project does not contain this type. This can happen if the service implementation type name changes after you generate the disconnected service agent. You cannot use the Update Disconnected Service Agent recipe to update the selected disconnected service agent. Instead, you can manually update the source code of the existing disconnected service agent or use the Create Disconnected Service Agent re [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProxyClassnotFoundMessage {
            get {
                return ResourceManager.GetString("ProxyClassnotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute {0} is required for this value provider..
        /// </summary>
        internal static string RequiredAttributeNotPresent {
            get {
                return ResourceManager.GetString("RequiredAttributeNotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        internal static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot locate service {0}..
        /// </summary>
        internal static string ServiceMissing {
            get {
                return ResourceManager.GetString("ServiceMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution build failed. The recipe could not be executed..
        /// </summary>
        internal static string SolutionBuildFailed {
            get {
                return ResourceManager.GetString("SolutionBuildFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution must be build to execute the current recipe..
        /// </summary>
        internal static string SolutionMustBeBuildToRunTheRecipe {
            get {
                return ResourceManager.GetString("SolutionMustBeBuildToRunTheRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the dlls {0} are not present in the folder.
        /// </summary>
        internal static string SupportingLibrariesNotPresent {
            get {
                return ResourceManager.GetString("SupportingLibrariesNotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid namespace is required.
        /// </summary>
        internal static string ValidNamespaceRequired {
            get {
                return ResourceManager.GetString("ValidNamespaceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View name must be a valid identifier.
        /// </summary>
        internal static string ViewNameMustBeValidIdentifier {
            get {
                return ResourceManager.GetString("ViewNameMustBeValidIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View name cannot be empty.
        /// </summary>
        internal static string ViewNameRequired {
            get {
                return ResourceManager.GetString("ViewNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hierarchy is not a project..
        /// </summary>
        internal static string VsHierarchyNotProject {
            get {
                return ResourceManager.GetString("VsHierarchyNotProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A WPF view file named &apos;{0}&apos; already exists. You can&apos;t add a non WPF view with the same name..
        /// </summary>
        internal static string YouCantAddFormsViewIfWpfViewExists {
            get {
                return ResourceManager.GetString("YouCantAddFormsViewIfWpfViewExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A non WPF view file named &apos;{0}&apos; already exists. You can&apos;t add a WPF view with the same name..
        /// </summary>
        internal static string YouCantAddWpfViewIfFormsViewExists {
            get {
                return ResourceManager.GetString("YouCantAddWpfViewIfFormsViewExists", resourceCulture);
            }
        }
    }
}
