//===============================================================================
// Microsoft patterns & practices
// Smart Client Software Factory 2010
//===============================================================================
// Copyright (c) Microsoft Corporation.  All rights reserved.
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY
// OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT
// LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
// FITNESS FOR A PARTICULAR PURPOSE.
//===============================================================================
// The example companies, organizations, products, domain names,
// e-mail addresses, logos, people, places, and events depicted
// herein are fictitious.  No association with any real company,
// organization, product, domain name, email address, logo, person,
// places, or events is intended or should be inferred.
//===============================================================================
//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add View" recipe.
//
// A presenter calls methods of a view to update the information that the view displays. 
// The view exposes its methods through an interface definition, and the presenter contains
// a reference to the view interface. This allows you to test the presenter with different 
// implementations of a view (for example, a mock view).
//
// For more information see:
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.scsf.2006jun/SCSF/html/03-030-Model%20View%20Presenter%20%20MVP%20.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

using GlobalBank.Infrastructure.Interface;
using GlobalBank.Infrastructure.Interface.BusinessEntities;
using Microsoft.Practices.CompositeUI;
using Microsoft.Practices.ObjectBuilder;

namespace GlobalBank.CreditCardAccounts.Module
{
	public class CreditCardAccountViewPresenter : Presenter<ICreditCardAccountView>
	{
		private CreditCard _creditCardSelected;
		private WorkItem _workItem;

		[InjectionConstructor]
		public CreditCardAccountViewPresenter(
			[ServiceDependency] WorkItem workItem,
			[ComponentDependency("CreditCard")] CreditCard creditCardSelected)
		{
			_workItem = workItem;
			_creditCardSelected = creditCardSelected;
		}

		public void OnCloseView()
		{
			_workItem.Items.Remove(_creditCardSelected);
			CloseView();
		}

		public string GetCreditCardLast4Digits()
		{
			return _creditCardSelected.CreditCardNumber.Substring(_creditCardSelected.CreditCardNumber.Length - 4);
		}
	}
}
