//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalBank.BranchSystems.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GlobalBank.BranchSystems.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Reason / Add To Queue.
        /// </summary>
        internal static string AddReasonTitle {
            get {
                return ResourceManager.GetString("AddReasonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Visitor To Queue.
        /// </summary>
        internal static string AddVisitorTitle {
            get {
                return ResourceManager.GetString("AddVisitorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add the selected customer to the queue. It&apos;s already in the queue..
        /// </summary>
        internal static string CustomerAlreadyInQueueMessage {
            get {
                return ResourceManager.GetString("CustomerAlreadyInQueueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue Service Message.
        /// </summary>
        internal static string CustomerAlreadyInQueueTitle {
            get {
                return ResourceManager.GetString("CustomerAlreadyInQueueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an unexpected problem contacting the Customer Finder service..
        /// </summary>
        internal static string CustomerFinderServiceFailure {
            get {
                return ResourceManager.GetString("CustomerFinderServiceFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer queue could not be refreshed. Service is unavailable..
        /// </summary>
        internal static string CustomerQueueServiceDownMessage {
            get {
                return ResourceManager.GetString("CustomerQueueServiceDownMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manages the customer queue.
        /// </summary>
        internal static string CustomerQueueViewDescription {
            get {
                return ResourceManager.GetString("CustomerQueueViewDescription", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon CustomerQueueViewIcon {
            get {
                object obj = ResourceManager.GetObject("CustomerQueueViewIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Queue.
        /// </summary>
        internal static string CustomerQueueViewText {
            get {
                return ResourceManager.GetString("CustomerQueueViewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the customer summary.
        /// </summary>
        internal static string CustomerSummaryViewDescription {
            get {
                return ResourceManager.GetString("CustomerSummaryViewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string CustomerSummaryViewTitle {
            get {
                return ResourceManager.GetString("CustomerSummaryViewTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap DefaultBackground {
            get {
                object obj = ResourceManager.GetObject("DefaultBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Customer.
        /// </summary>
        internal static string FindCustomerLabelText {
            get {
                return ResourceManager.GetString("FindCustomerLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Customer Results Description.
        /// </summary>
        internal static string FindCustomerResultsViewDescription {
            get {
                return ResourceManager.GetString("FindCustomerResultsViewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Customer Results.
        /// </summary>
        internal static string FindCustomerResultsViewTitle {
            get {
                return ResourceManager.GetString("FindCustomerResultsViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the customer information.
        /// </summary>
        internal static string FindCustomerViewDescription {
            get {
                return ResourceManager.GetString("FindCustomerViewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Customer.
        /// </summary>
        internal static string FindCustomerViewTitle {
            get {
                return ResourceManager.GetString("FindCustomerViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the officer&apos;s assigned customers.
        /// </summary>
        internal static string MyCustomersQueueViewDescription {
            get {
                return ResourceManager.GetString("MyCustomersQueueViewDescription", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon MyCustomersQueueViewIcon {
            get {
                object obj = ResourceManager.GetObject("MyCustomersQueueViewIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found. Please try again..
        /// </summary>
        internal static string NoCustomerFoundMessage {
            get {
                return ResourceManager.GetString("NoCustomerFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Visitor to Queue.
        /// </summary>
        internal static string QueueVisitorLabelText {
            get {
                return ResourceManager.GetString("QueueVisitorLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string ReadyMessage {
            get {
                return ResourceManager.GetString("ReadyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Customer.
        /// </summary>
        internal static string ServiceCustomerLabelText {
            get {
                return ResourceManager.GetString("ServiceCustomerLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many customers match the search criteria. Try to refine your search to narrow the results..
        /// </summary>
        internal static string TooManyResultsMessage {
            get {
                return ResourceManager.GetString("TooManyResultsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [a-zA-Z\b ].
        /// </summary>
        internal static string ValidCharForNames {
            get {
                return ResourceManager.GetString("ValidCharForNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [\w\.\@ ].
        /// </summary>
        internal static string ValidEmailChar {
            get {
                return ResourceManager.GetString("ValidEmailChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [a-zA-Z0-9\-\.\b ].
        /// </summary>
        internal static string ValidGeneralChar {
            get {
                return ResourceManager.GetString("ValidGeneralChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [0-9\b].
        /// </summary>
        internal static string ValidNumeralChar {
            get {
                return ResourceManager.GetString("ValidNumeralChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [0-9\b\-].
        /// </summary>
        internal static string ValidNumeralDashChar {
            get {
                return ResourceManager.GetString("ValidNumeralDashChar", resourceCulture);
            }
        }
    }
}
