'===============================================================================
' Microsoft patterns & practices
' CompositeUI Application Block
'===============================================================================
' Copyright © Microsoft Corporation.  All rights reserved.
' THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY
' OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT
' LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
' FITNESS FOR A PARTICULAR PURPOSE.
'===============================================================================

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50215.44
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

' 
' This source code was auto-generated by xsd, Version=2.0.50215.44.
' 

Imports Microsoft.VisualBasic
Imports System.Xml.Serialization


''' <remarks/>
<System.SerializableAttribute(), System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://schemas.microsoft.com/pag/cab-command-map"), System.Xml.Serialization.XmlRootAttribute(Namespace:="http://schemas.microsoft.com/pag/cab-command-map", IsNullable:=False)> _
Partial Public Class CommandMap

	Private mappingField As Mapping()

	''' <remarks/>
	<System.Xml.Serialization.XmlElementAttribute("Mapping")> _
	Public Property Mapping() As Mapping()
		Get
			Return Me.mappingField
		End Get
		Set(ByVal value As Mapping())
			Me.mappingField = value
		End Set
	End Property
End Class

''' <remarks/>
<System.SerializableAttribute(), System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://schemas.microsoft.com/pag/cab-command-map")> _
Partial Public Class Mapping

	Private siteField As String

	Private commandNameField As String

	Private labelField As String

	''' <remarks/>
	<System.Xml.Serialization.XmlAttributeAttribute()> _
	Public Property Site() As String
		Get
			Return Me.siteField
		End Get
		Set(ByVal value As String)
			Me.siteField = value
		End Set
	End Property

	''' <remarks/>
	<System.Xml.Serialization.XmlAttributeAttribute()> _
	Public Property CommandName() As String
		Get
			Return Me.commandNameField
		End Get
		Set(ByVal value As String)
			Me.commandNameField = value
		End Set
	End Property

	''' <remarks/>
	<System.Xml.Serialization.XmlAttributeAttribute()> _
	Public Property Label() As String
		Get
			Return Me.labelField
		End Get
		Set(ByVal value As String)
			Me.labelField = value
		End Set
	End Property
End Class
