//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add View" recipe.
//
// For more information see: 
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.scsf.2006jun/SCSF/html/03-030-Model%20View%20Presenter%20%20MVP%20.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace GlobalBank.BasicAccounts.Module
{
	partial class PurchaseCDView
	{
		/// <summary>
		/// The presenter used by this view.
		/// </summary>
		private GlobalBank.BasicAccounts.Module.PurchaseCDViewPresenter _presenter = null;

		/// <summary> 
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary> 
		/// Clean up any resources being used.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose(bool disposing)
		{
			if (disposing)
			{
				if (_presenter != null)
					_presenter.Dispose();

				if (components != null)
					components.Dispose();
			}

			base.Dispose(disposing);
		}

		#region Component Designer generated code

		/// <summary> 
		/// Required method for Designer support - do not modify 
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
			this.components = new System.ComponentModel.Container();
			System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(PurchaseCDView));
			System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
			this.buttonCancel = new System.Windows.Forms.Button();
			this.buttonExecute = new System.Windows.Forms.Button();
			this._labelDuration = new System.Windows.Forms.Label();
			this._labelAmount = new System.Windows.Forms.Label();
			this._amountTextBox = new System.Windows.Forms.MaskedTextBox();
			this._ratesGridView = new System.Windows.Forms.DataGridView();
			this._labelRate = new System.Windows.Forms.Label();
			this._rateTextBox = new System.Windows.Forms.MaskedTextBox();
			this._labelRates = new System.Windows.Forms.Label();
			this._buttonGetRate = new System.Windows.Forms.Button();
			this.label1 = new System.Windows.Forms.Label();
			this._accountsComboBox = new System.Windows.Forms.ComboBox();
			this._accountBindingSource = new System.Windows.Forms.BindingSource(this.components);
			this._durationTextbox = new System.Windows.Forms.MaskedTextBox();
			this._messageLabel = new System.Windows.Forms.Label();
			this._approveLink = new System.Windows.Forms.LinkLabel();
			((System.ComponentModel.ISupportInitialize)(this._ratesGridView)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this._accountBindingSource)).BeginInit();
			this.SuspendLayout();
			// 
			// buttonCancel
			// 
			resources.ApplyResources(this.buttonCancel, "buttonCancel");
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseVisualStyleBackColor = true;
			this.buttonCancel.Click += new System.EventHandler(this.buttonCancel_Click);
			// 
			// buttonExecute
			// 
			resources.ApplyResources(this.buttonExecute, "buttonExecute");
			this.buttonExecute.Name = "buttonExecute";
			this.buttonExecute.UseVisualStyleBackColor = true;
			this.buttonExecute.Click += new System.EventHandler(this.buttonExecute_Click);
			// 
			// _labelDuration
			// 
			resources.ApplyResources(this._labelDuration, "_labelDuration");
			this._labelDuration.Name = "_labelDuration";
			// 
			// _labelAmount
			// 
			resources.ApplyResources(this._labelAmount, "_labelAmount");
			this._labelAmount.Name = "_labelAmount";
			// 
			// _amountTextBox
			// 
			resources.ApplyResources(this._amountTextBox, "_amountTextBox");
			this._amountTextBox.Name = "_amountTextBox";
			this._amountTextBox.TextMaskFormat = System.Windows.Forms.MaskFormat.ExcludePromptAndLiterals;
			this._amountTextBox.TextChanged += new System.EventHandler(this._amountTextBox_TextChanged);
			// 
			// _ratesGridView
			// 
			this._ratesGridView.AllowUserToAddRows = false;
			this._ratesGridView.AllowUserToDeleteRows = false;
			this._ratesGridView.AllowUserToResizeColumns = false;
			this._ratesGridView.AllowUserToResizeRows = false;
			resources.ApplyResources(this._ratesGridView, "_ratesGridView");
			this._ratesGridView.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
			this._ratesGridView.Name = "_ratesGridView";
			this._ratesGridView.ReadOnly = true;
			this._ratesGridView.RowHeadersVisible = false;
			this._ratesGridView.RowHeadersWidthSizeMode = System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing;
			dataGridViewCellStyle1.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
			this._ratesGridView.RowsDefaultCellStyle = dataGridViewCellStyle1;
			this._ratesGridView.ShowCellErrors = false;
			this._ratesGridView.ShowCellToolTips = false;
			this._ratesGridView.ShowEditingIcon = false;
			this._ratesGridView.ShowRowErrors = false;
			// 
			// _labelRate
			// 
			resources.ApplyResources(this._labelRate, "_labelRate");
			this._labelRate.Name = "_labelRate";
			// 
			// _rateTextBox
			// 
			resources.ApplyResources(this._rateTextBox, "_rateTextBox");
			this._rateTextBox.Name = "_rateTextBox";
			this._rateTextBox.TextMaskFormat = System.Windows.Forms.MaskFormat.IncludePromptAndLiterals;
			// 
			// _labelRates
			// 
			resources.ApplyResources(this._labelRates, "_labelRates");
			this._labelRates.Name = "_labelRates";
			// 
			// _buttonGetRate
			// 
			resources.ApplyResources(this._buttonGetRate, "_buttonGetRate");
			this._buttonGetRate.Name = "_buttonGetRate";
			this._buttonGetRate.UseVisualStyleBackColor = true;
			this._buttonGetRate.Click += new System.EventHandler(this._buttonGetRate_Click);
			// 
			// label1
			// 
			resources.ApplyResources(this.label1, "label1");
			this.label1.Name = "label1";
			// 
			// _accountsComboBox
			// 
			this._accountsComboBox.DataSource = this._accountBindingSource;
			this._accountsComboBox.DisplayMember = "FriendlyName";
			this._accountsComboBox.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
			this._accountsComboBox.FormattingEnabled = true;
			resources.ApplyResources(this._accountsComboBox, "_accountsComboBox");
			this._accountsComboBox.Name = "_accountsComboBox";
			this._accountsComboBox.ValueMember = "AccountNumber";
			// 
			// _accountBindingSource
			// 
			this._accountBindingSource.DataSource = typeof(GlobalBank.Infrastructure.Interface.BusinessEntities.Account);
			// 
			// _durationTextbox
			// 
			this._durationTextbox.HidePromptOnLeave = true;
			resources.ApplyResources(this._durationTextbox, "_durationTextbox");
			this._durationTextbox.Name = "_durationTextbox";
			this._durationTextbox.TextMaskFormat = System.Windows.Forms.MaskFormat.ExcludePromptAndLiterals;
			this._durationTextbox.TextChanged += new System.EventHandler(this._durationTextbox_TextChanged);
			// 
			// _messageLabel
			// 
			resources.ApplyResources(this._messageLabel, "_messageLabel");
			this._messageLabel.ForeColor = System.Drawing.Color.DarkRed;
			this._messageLabel.Name = "_messageLabel";
			// 
			// _approveLink
			// 
			resources.ApplyResources(this._approveLink, "_approveLink");
			this._approveLink.Name = "_approveLink";
			this._approveLink.TabStop = true;
			this._approveLink.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this._approveLink_LinkClicked);
			// 
			// PurchaseCDView
			// 
			resources.ApplyResources(this, "$this");
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.Controls.Add(this._approveLink);
			this.Controls.Add(this._messageLabel);
			this.Controls.Add(this._accountsComboBox);
			this.Controls.Add(this.label1);
			this.Controls.Add(this._buttonGetRate);
			this.Controls.Add(this._labelRates);
			this.Controls.Add(this._durationTextbox);
			this.Controls.Add(this._rateTextBox);
			this.Controls.Add(this._labelRate);
			this.Controls.Add(this._ratesGridView);
			this.Controls.Add(this._amountTextBox);
			this.Controls.Add(this._labelAmount);
			this.Controls.Add(this._labelDuration);
			this.Controls.Add(this.buttonExecute);
			this.Controls.Add(this.buttonCancel);
			this.Name = "PurchaseCDView";
			((System.ComponentModel.ISupportInitialize)(this._ratesGridView)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this._accountBindingSource)).EndInit();
			this.ResumeLayout(false);
			this.PerformLayout();

		}

		#endregion

		private System.Windows.Forms.Button buttonCancel;
		private System.Windows.Forms.Button buttonExecute;
        private System.Windows.Forms.Label _labelDuration;
		private System.Windows.Forms.Label _labelAmount;
		private System.Windows.Forms.MaskedTextBox _amountTextBox;
		private System.Windows.Forms.DataGridView _ratesGridView;
		private System.Windows.Forms.Label _labelRate;
		private System.Windows.Forms.MaskedTextBox _rateTextBox;
		private System.Windows.Forms.Label _labelRates;
		private System.Windows.Forms.Button _buttonGetRate;
		private System.Windows.Forms.Label label1;
        private System.Windows.Forms.ComboBox _accountsComboBox;
        private System.Windows.Forms.BindingSource _accountBindingSource;
        private System.Windows.Forms.MaskedTextBox _durationTextbox;
		private System.Windows.Forms.Label _messageLabel;
        private System.Windows.Forms.LinkLabel _approveLink;
	}
}

