//===============================================================================
// Microsoft patterns & practices
// Smart Client Software Factory 2010
//===============================================================================
// Copyright (c) Microsoft Corporation.  All rights reserved.
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY
// OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT
// LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
// FITNESS FOR A PARTICULAR PURPOSE.
//===============================================================================
// The example companies, organizations, products, domain names,
// e-mail addresses, logos, people, places, and events depicted
// herein are fictitious.  No association with any real company,
// organization, product, domain name, email address, logo, person,
// places, or events is intended or should be inferred.
//===============================================================================
//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add View" recipe.
//
// A presenter calls methods of a view to update the information that the view displays. 
// The view exposes its methods through an interface definition, and the presenter contains
// a reference to the view interface. This allows you to test the presenter with different 
// implementations of a view (for example, a mock view).
//
// For more information see:
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.scsf.2006jun/SCSF/html/03-030-Model%20View%20Presenter%20%20MVP%20.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

using System;
using Microsoft.Practices.ObjectBuilder;
using Microsoft.Practices.CompositeUI;
using Microsoft.Practices.QuickStarts.WPFIntegration.Infrastructure.Interface;
using Microsoft.Practices.QuickStarts.WPFIntegration.EmployeeData.Services;
using Microsoft.Practices.CompositeUI.EventBroker;
using Microsoft.Practices.QuickStarts.WPFIntegration.EmployeeData.Constants;
using System.Xml;
using Microsoft.Practices.CompositeUI.Utility;
using Microsoft.Practices.QuickStarts.WPFIntegration.EmployeeData.BusinessEntities;

namespace Microsoft.Practices.QuickStarts.WPFIntegration.EmployeeData
{
    public class EmployeeViewPresenter : Presenter<IEmployeeView>
    {
        private EmployeeService _service;

        [ServiceDependency]
        public EmployeeService EmployeeService
        {
            get { return _service; }
            set { _service = value; }
        }
	
        /// <summary>
        /// This method is a placeholder that will be called by the view when it's been loaded <see cref="System.Winforms.Control.OnLoad"/>
        /// </summary>
        public override void OnViewReady()
        {
            base.OnViewReady();
        }

        /// <summary>
        /// Close the view
        /// </summary>
        public void OnCloseView()
        {
            base.CloseView();
        }

        [EventSubscription(EventTopicNames.PositionSelected, ThreadOption.UserInterface)]
        public void OnPositionSelected(object sender, DataEventArgs<XmlElement> eventArgs)
        {
            int id = Int32.Parse( eventArgs.Data.Attributes["ID"].Value );
            Employee employee = EmployeeService.GetEmployee(id);
            View.ShowEmployee(employee);
        }
    }
}

