//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.21006.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Practices.SmartClient.ConnectionMonitor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Practices.SmartClient.ConnectionMonitor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DestNetworkName: .
        /// </summary>
        internal static string DestNetworkName {
            get {
                return ResourceManager.GetString("DestNetworkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed Information.
        /// </summary>
        internal static string DetailedInfoTitle {
            get {
                return ResourceManager.GetString("DetailedInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ********************.
        /// </summary>
        internal static string DetailedInfoTitle2 {
            get {
                return ResourceManager.GetString("DetailedInfoTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdapterName: {0}.
        /// </summary>
        internal static string DetailedStatusAdapterName {
            get {
                return ResourceManager.GetString("DetailedStatusAdapterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectionStatus: {0}.
        /// </summary>
        internal static string DetailedStatusConnectionStatus {
            get {
                return ResourceManager.GetString("DetailedStatusConnectionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags: {0}.
        /// </summary>
        internal static string DetailedStatusFlags {
            get {
                return ResourceManager.GetString("DetailedStatusFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GuidDestNet: {0}.
        /// </summary>
        internal static string DetailedStatusGuidDestNet {
            get {
                return ResourceManager.GetString("DetailedStatusGuidDestNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GuidSourceNet: {0}.
        /// </summary>
        internal static string DetailedStatusGuidSourceNet {
            get {
                return ResourceManager.GetString("DetailedStatusGuidSourceNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPAddressInfo: {0}.
        /// </summary>
        internal static string DetailedStatusIPAddressInfo {
            get {
                return ResourceManager.GetString("DetailedStatusIPAddressInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastConnectionTime: {0}/{1}/{2}-{3}:{4}:{5}.
        /// </summary>
        internal static string DetailedStatusLastConnectionTime {
            get {
                return ResourceManager.GetString("DetailedStatusLastConnectionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure: {0}.
        /// </summary>
        internal static string DetailedStatusSecure {
            get {
                return ResourceManager.GetString("DetailedStatusSecure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignalQuality: {0}.
        /// </summary>
        internal static string DetailedStatusSignalQuality {
            get {
                return ResourceManager.GetString("DetailedStatusSignalQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtype: {0}.
        /// </summary>
        internal static string DetailedStatusSubtype {
            get {
                return ResourceManager.GetString("DetailedStatusSubtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The network named &apos;{0}&apos; is already in the NetwrokCollection..
        /// </summary>
        internal static string DuplicatedNetworkError {
            get {
                return ResourceManager.GetString("DuplicatedNetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error enumerating the wireless adapters using the Native WiFi API.
        /// </summary>
        internal static string ErrorEnumeratingWirelessAdapters {
            get {
                return ResourceManager.GetString("ErrorEnumeratingWirelessAdapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WifiEnumerator is not supported in the current OS. It requires Windows XP SP2 or later..
        /// </summary>
        internal static string ErrorUnsupportedOS {
            get {
                return ResourceManager.GetString("ErrorUnsupportedOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnMonitorQueryDetailedStatus has failed. HResult = {0}.
        /// </summary>
        internal static string ExceptionDetailedStatusQueryFailed {
            get {
                return ResourceManager.GetString("ExceptionDetailedStatusQueryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetStringFromIPInfo has failed. HResult = {0}.
        /// </summary>
        internal static string ExceptionGetStringFromIPFailed {
            get {
                return ResourceManager.GetString("ExceptionGetStringFromIPFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection monitor instance should be initialized first..
        /// </summary>
        internal static string InstanceNotInitialized {
            get {
                return ResourceManager.GetString("InstanceNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -------------------------------------\r\n.
        /// </summary>
        internal static string LineSeparator {
            get {
                return ResourceManager.GetString("LineSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Winsock helper call failed. Result code was {0}.
        /// </summary>
        internal static string WinsockError {
            get {
                return ResourceManager.GetString("WinsockError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The aforementioned dll was not found in your system. Make sure Wireless LAN Services are installed..
        /// </summary>
        internal static string WlanapiNotFound {
            get {
                return ResourceManager.GetString("WlanapiNotFound", resourceCulture);
            }
        }
    }
}
